pipeline {
    agent any

    tools {
        maven "Maven"
    }
    stages {
        stage('Build'){
            steps{
                dir("my-app")
                bat "mvn clean package"
            }
        }
        stage('Test') {
            steps {
                dir("my-app")
                bat 'mvn test'
            }
    post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                bat './jenkins/scripts/deliver.bat'
            }
        }
    }
}


